# Change these first
owner: GentlemanHu # Your GitHub username
repo: own-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Book Library
    url: https://store.crushing.xyz
  - name: OneDrive
  - name: Blog xyz
    url: https://blog.crushing.xyz
  - name: Read xyz
    url: https://read.crushing.xyz
  - name: WWWW xyz
    url: https://www.crushing.xyz
  - name: Jupyter Lab
    url: https://jupyter.crushing.xyz
  - name: AI flowise
    url: https://aiflow.crushing.xyz
  - name: Local Stable Diffusion
    url: https://sd.crushing.xyz
  - name: ChatGPT Next
    url: https://gpt.crushing.xyz
    
assignees:
  - Gentleman.Hu

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  publish: true
  cname: up.crushing.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /own-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Gentleman.Hu
  introTitle: "完美"
  introMessage: "一些自用站点服务状态"
  navbar:
    - title: Own Site Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
