# Change these first
owner: GentlemanHu # Your GitHub username
repo: own-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Keep Pie
    url: https://pie.keepfuture.live
  - name: Vps Status
    url: https://status.devfly.top
  - name: OwnCloud API
    url: https://api.justfeeling.me
  - name: RestCloud API
    url: https://api.crushing.xyz/api/v1/test/template
  - name: Book Library
    url: https://book.crushing.xyz
  - name: OneDrive
    url: https://pan.devfly.top
  - name: Own VSCode
    url: https://code.crushing.xyz
  - name: Own IDE
    url: https://ide.crushing.xyz
  - name: Own OS
    url: https://os.crushing.xyz
  - name: Portainer
    url: https://get.crushing.xyz
  - name: Monit
    url: https://monit.devfly.top
  - name: Blog xyz
    url: https://blog.crushing.xyz
  - name: Read xyz
    url: https://read.crushing.xyz
  - name: WWWW xyz
    url: https://www.crushing.xyz
  - name: Note
    url: https://note.justfeeling.me
  - name: Cloud60 Code
    url: https://vscode.devfly.top
  - name: Jupyter Lab
    url: https://lab.devfly.top
  - name: GD-TG bot
    url: https://bot.devfly.top/api/gdurl/count
    
assignees:
  - Gentleman.Hu

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  publish: true
  cname: status.codecho.top
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /own-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Gentleman.Hu
  introTitle: "完美"
  introMessage: "一些自用站点服务状态"
  navbar:
    - title: Own Site Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
